name: Deploy React SPA to Aliyun ECS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: main
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Deploy to Aliyun Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: ".next/*"
          target:
            ${{ secrets.TARGET }}

            # Execute build and start commands on ECS
      - name: Build and Start on Aliyun ECS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Enter target directory
            cd /root/next-app
            # Clone or pull repository
            git pull origin main
            # Install PM2 if not present
            npm install -g pm2
            # Install dependencies
            npm install --force
            # Build Next.js project
            npm run build
            # Stop existing process (if any)
            pm2 stop nextjs-app || true
            # Start or restart Next.js service
            pm2 start npm --name "nextjs-app" -- start
            # Restart Nginx
            sudo systemctl restart nginx
